### ISSUE TITLE
Website Icon

### ISSUE THREAD

**Issue by Bhitt** [uss-moon/Shuffling#10]
Create a unique icon/brand for the website.
Possibly find some mtg icons that we are allowed to use.

**Comment by mpatel1996** [comment]
Website Logo
![TS](https://user-images.githubusercontent.com/28855058/68989695-1181de00-07ff-11ea-8637-fe3abbd7ac3b.png)

Favicon Logo
![TS_42](https://user-images.githubusercontent.com/28855058/68989696-1a72af80-07ff-11ea-9ca9-61ba39831058.png)

**Comment by Bhitt** [comment]
Looks great
