### ISSUE TITLE
Website Design/Flow

### ISSUE THREAD

**Issue by Bhitt** [uss-moon/Shuffling#5]
We need some blueprint designs of how the website will look or flow (where features are displayed/color schemes/ etc). How do we best display the cards/collections while also complementing the art that is present on the cards themselves?

**Comment by mpatel1996** [comment]
![Web1](https://user-images.githubusercontent.com/28855058/65935719-f71aaf00-e3ce-11e9-8794-f1595cd01884.png)
![web2](https://user-images.githubusercontent.com/28855058/65935720-f71aaf00-e3ce-11e9-810e-911ceb45211c.png)
