### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by Bhitt** [uss-moon/Shuffling#7]
What components of Bootstrap should we use? Can you create a demo page that uses a feature from bootstrap you want to use?
Should we use a CDN for bootstrap or just download it and host it on the servers local files?
How can we accomplish pagination best? Is it through bootstrap's pagination component or by our own methods?

**Comment by obyou12** [comment]
We are using Bootstrap 4.3 because it is much easy to handle and looks good!
